apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: url-shorten
  labels:
    app: url-svc
type: Opaque
stringData:
  # DEV environment token
  dev-token: "dev-root-token"
  # PROD environment token (CHANGE THIS IN PRODUCTION!)
  prod-token: "prod-root-token"
